config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create!(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClose</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<% if user_signed_in?%>
  <h1>Tweets</h1>
  <%= link_to 'Make a tweet', new_tweet_path %>
  <ol>
    <% @tweets.each do |tweet| %>
      <li>
        <p><%= tweet.user.username %></p>
        <p><%= tweet.title %></p>
        <p><%= tweet.body %></p>
        <p><%= link_to 'View', tweet %></p>
      </li>
    <% end %>
  </ol>
<% else %>
  <h1>Create an account!</h1>
  <%= link_to 'Click here!', new_user_registration_path %>
<% end %>

app/views/tweets/new.html.erb
<h1>Create Tweet</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path %>

app/views/tweets/show.html.erb
<h1>View your tweet</h1>
<p>Title: <%= @tweet.title %></p>
<p>Message: <%= @tweet.body %></p>

<%= link_to 'Home', root_path %>